services:

  backend:
    build:
      context: ./Natillera.Backend
      dockerfile: Dockerfile
    container_name: natillera-backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      CORS_ORIGINS: ${CORS_ORIGINS}
    depends_on:
      postgres:
        condition: service_healthy

  web:
    build:
      context: ./Natillera.Frontend
      dockerfile: Dockerfile
    container_name: natillera-web
    ports:
      - "3000:80"
    depends_on:
      - backend

  postgres:
    image: postgres:18-alpine
    container_name: natillera-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d natillera"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
